### ISSUE TITLE
Question: Why there are duplicities in package.json and project.clj?

### ISSUE THREAD

**Issue by tommmyy** [gothinkster/clojurescript-reframe-realworld-example-app#2]
Sorry for newbie question.

`project.clj`
```clj
:npm-deps {"react" "15.6.2"
                     "react-dom" "15.6.2"
                     "create-react-class" "15.6.2"}}}}})
```

`package.json`
```json
{
  "dependencies": {
    "@cljs-oss/module-deps": "^1.1.1",
    "create-react-class": "^15.6.2",
    "react": "^15.6.2",
    "react-dom": "^15.6.2"
  }
}
```

Thank you for the answer!

**Comment by KingMob** [comment]
Listing libs in `:npm-deps` in project.clj will make Clojurescript attempt to manage those libs in package.json for you. But since npm/yarn don't understand project.clj, it copies those libs to package.json.

**Comment by tommmyy** [comment]
@KingMob Thank you for the answer!
