### ISSUE TITLE
Wrong README clone url

### ISSUE THREAD

**Issue by ampersanda** [gothinkster/clojurescript-reframe-realworld-example-app#4]
Hi,

I read the README file and it says that I had to clone the re-frame repo from `git clone https://github.com/jacekschae/conduit`

It should be `git clone https://github.com/gothinkster/clojurescript-reframe-realworld-example-app.git` right?

**Comment by dijonkitchen** [comment]
The link in the Readme is referencing the source repository which seems to have been merged in here with the rest of the "RealWorld" examples. 

@jacekschae can you merge in your changes so the two repos are consistent and maybe just make changes on this one so people aren't confused?

**Comment by jacekschae** [comment]
Sorry for being a bit late on this one. I'll depriciate this repo and forward people to https://github.com/jacekschae/conduit where it is maintained. The only reason why this situation exists  - two repos with the same content was lack of response from gothinkster when I crearted it. Only later they create a repo and added me as mainter.
